# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the OneESPT template 
# If you are not using the E+D shared hosted pool with windows-2022, replace the pool section with your hosted pool, os, and image name. If you are using a Linux image, you must specify an additional windows image for SDL: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#how-to-specify-a-windows-pool-for-the-sdl-source-analysis-stage
# The Task 'PublishBuildArtifacts@1' have been converted to an output named '' in the templateContext section.
trigger:
  branches:
    include:
    - main
    - develop
    - features/cartier-synapse-collab
  paths:
    include:
    - Synapse/Cartier/*
schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: Build_stage
      jobs:
      - job: job
        steps:
        - task: CredScan@3
          inputs:
            debugMode: false
          condition: succeededOrFailed()
          displayName: 'Run Credential Scanner'

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.10'
            addToPath: true

        - task: PipAuthenticate@1
          inputs:
            artifactFeeds: 'OneITVSO/HR-TIME-TimeLeaveShiftSchedCartier'

        - pwsh: |
            $ErrorActionPreference = "Stop"
            python -m pip install --upgrade pip
            Get-Content requirements.txt | ForEach-Object {
              pip install $_
              if ($LASTEXITCODE -ne 0) {
                exit $LASTEXITCODE
              }
            }
          workingDirectory: '$(System.DefaultWorkingDirectory)\InfraDeployment'
          displayName: 'Install dependencies'

        - task: PowerShell@2
          displayName: 'Convert Notebook to Python'
          inputs:
            targetType: 'filePath'
            filePath: '$(System.DefaultWorkingDirectory)\InfraDeployment\scripts\ConvertNotebookJsonToPython.ps1'
            arguments: '-SourceFile "$(System.DefaultWorkingDirectory)\Synapse\Cartier\notebook\unit_test_runner.json" -DestinationFile "$(System.DefaultWorkingDirectory)\Synapse\Cartier\test_unit_test_runner.py"'

        - script: |
            pytest $(System.DefaultWorkingDirectory)/Synapse/Cartier/test_unit_test_runner.py --cov=$(System.DefaultWorkingDirectory)/Synapse/Cartier --cov-report=xml:coverage.xml --junitxml=test-results.xml
          displayName: 'Run tests with coverage'
          continueOnError: true

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test-results.xml'
          displayName: 'Publish test results'
          condition: succeededOrFailed()

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          displayName: 'Publish code coverage results'
          condition: succeededOrFailed()

        - task: PowerShell@2
          displayName: 'Verify Code Coverage'
          inputs:
            targetType: 'inline'
            script: |
              [xml]$coverageData = Get-Content $(System.DefaultWorkingDirectory)\coverage.xml
                    $lineRate = [double]$coverageData.coverage.'line-rate'
                    $threshold = 0.70
                    if ($lineRate -lt $threshold) {
                        Write-Error "Code coverage ($([math]::Round($lineRate*100,2))%) is below the threshold ($([math]::Round($threshold*100,2))%)"
                        exit 1
                    } else {
                        Write-Output "Code coverage ($([math]::Round($lineRate*100,2))%) is above the threshold"
                    }
          condition: succeededOrFailed()
          continueOnError: true

        - task: Synapse workspace deployment@2
          inputs:
            operation: 'validate'
            ArtifactsFolder: '$(System.DefaultWorkingDirectory)/Synapse/Cartier'
            azureSubscription: 'MSFT - Workforce Software Integrations -ServiceConnection'
            ResourceGroupName: 'RG-Cartier-Dev'
            TargetWorkspaceName: 'synw-time-cartier-dev'
            DeleteArtifactsNotInTemplate: false
            DeployManagedPrivateEndpoints: false
            FailOnMissingOverrides: false
            Environment: 'prod'
            npmpackage: 'prod'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/InfraDeployment/'
            Contents: '*requirements.txt'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'drop'
            publishLocation: 'Container'